/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;




import controller.ClsEvento;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modell.IdCliente;
import utilitarios.RecursosMetodos;
/**
 *

 */
public class FormEvento extends javax.swing.JFrame {

    ClsEvento clsE;
    double subtotal;
    IdCliente ide = new IdCliente();
    RecursosMetodos rm = new RecursosMetodos();
    DefaultTableModel modelo;
    ArrayList <IdCliente>tbPersona1;
    //ArrayList <IdProducto>tbPersona;
    
    public FormEvento() {
        initComponents();
        cargar_cab();
    }
    public void llenarTabla()
    {
        ide.setId(rm.contador());
        ide.setNombre(TxtNombres.getText());
        ide.setDireccion(TxtDireccion.getText());
        ide.setRuc(TxtRuc.getText());
        ide.setNombre(TxtProducto.getText());
        ide.setDireccion(TxtCantidad.getText());
        ide.setRuc(TxtPrecio.getText());
              
        clsE = new ClsEvento(ide);
        Integer.parseInt(TxtCantidad.getText());
        //Integer.parseInt(TxtPrecio.getText());
        double num = Double.parseDouble(TxtPrecio.getText());
        subtotal=TxtCantidad.getColumns() *TxtPrecio.getColumns();
    }
    public void cargar_cab(){
        modelo = new DefaultTableModel();
        modelo.addColumn("item");
        modelo.addColumn("producto");
        modelo.addColumn("cantidad");
        modelo.addColumn("precio");
        modelo.addColumn("subtotal");
        //modelo.addColumn("nombres");
        //modelo.addColumn("direccion");
        //modelo.addColumn("ruc");
        
        TableEvento.setModel(modelo);
    }
    public void limpiar_text(){
     //this.TxtNombres.setText("");
     //this.TxtDireccion.setText("");
     //this.TxtRuc.setText("");
     this.TxtProducto.setText("");
     this.TxtCantidad.setText("");
     this.TxtPrecio.setText("");
     enabled_text(true);
    }
    public void enabled_text(boolean estado){
     this.TxtNombres.enable(estado);
     this.TxtDireccion.enable(estado);
     this.TxtRuc.enable(estado);
     this.TxtProducto.enable(estado);
     this.TxtCantidad.enable(estado);
     this.TxtPrecio.enable(estado);
    }
    public void cargar_datos() {
        tbPersona1 = clsE.reportePersona();
        for(IdCliente idp1 : tbPersona1){
            modelo.addRow(new Object[]{idp1.getId(),
                                        idp1.getNombre(),
                                        idp1.getDireccion(),
                                        idp1.getRuc(),
                                       
                });
        }
        
    }
   
      
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtRuc = new javax.swing.JTextField();
        PanelBtnMain = new javax.swing.JPanel();
        BtnNuevo = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEvento = new javax.swing.JTable();
        PanelBtnSecond = new javax.swing.JPanel();
        BtnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtProducto = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos cliente"));
        PanelDatos.setEnabled(false);
        PanelDatos.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(" nombres:");
        PanelDatos.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 20);

        TxtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombresKeyPressed(evt);
            }
        });
        PanelDatos.add(TxtNombres);
        TxtNombres.setBounds(120, 20, 190, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Direccion:");
        PanelDatos.add(jLabel2);
        jLabel2.setBounds(10, 50, 100, 20);

        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyPressed(evt);
            }
        });
        PanelDatos.add(TxtDireccion);
        TxtDireccion.setBounds(120, 50, 100, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ruc:");
        PanelDatos.add(jLabel3);
        jLabel3.setBounds(10, 80, 100, 14);

        TxtRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRucKeyPressed(evt);
            }
        });
        PanelDatos.add(TxtRuc);
        TxtRuc.setBounds(120, 80, 100, 20);

        getContentPane().add(PanelDatos);
        PanelDatos.setBounds(0, 50, 440, 140);

        PanelBtnMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelBtnMain.setLayout(null);

        BtnNuevo.setText("Nuevo");
        BtnNuevo.setBorderPainted(false);
        BtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnNuevo.setIconTextGap(6);
        BtnNuevo.setVerifyInputWhenFocusTarget(false);
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        PanelBtnMain.add(BtnNuevo);
        BtnNuevo.setBounds(10, 10, 90, 20);

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        PanelBtnMain.add(BtnGuardar);
        BtnGuardar.setBounds(110, 10, 90, 20);

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        PanelBtnMain.add(BtnCancelar);
        BtnCancelar.setBounds(220, 10, 90, 20);

        getContentPane().add(PanelBtnMain);
        PanelBtnMain.setBounds(0, 10, 440, 40);

        TableEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableEvento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 260, 440, 90);

        PanelBtnSecond.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBtnSecond.setLayout(null);

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        PanelBtnSecond.add(BtnEliminar);
        BtnEliminar.setBounds(90, 3, 73, 23);

        getContentPane().add(PanelBtnSecond);
        PanelBtnSecond.setBounds(0, 230, 440, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("producto:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 47, 20);

        TxtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtProductoKeyPressed(evt);
            }
        });
        jPanel1.add(TxtProducto);
        TxtProducto.setBounds(60, 10, 60, 20);

        TxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCantidadKeyPressed(evt);
            }
        });
        jPanel1.add(TxtCantidad);
        TxtCantidad.setBounds(150, 10, 80, 20);

        TxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyPressed(evt);
            }
        });
        jPanel1.add(TxtPrecio);
        TxtPrecio.setBounds(250, 10, 70, 20);

        jButton1.setText("Save");
        jButton1.setActionCommand("Boton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 10, 57, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 190, 440, 40);

        jPanel2.setLayout(null);

        jLabel5.setText("TOTAL:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(300, 20, 50, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(360, 20, 59, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 350, 440, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
     
        llenarTabla();
        cargar_datos();
        limpiar_text();
        enabled_text(false);
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        limpiar_text();
        enabled_text(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        limpiar_text();
        enabled_text(true);
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void TxtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombresKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        this.TxtDireccion.requestFocus();
        }
    }//GEN-LAST:event_TxtNombresKeyPressed

    private void TxtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        this.TxtRuc.requestFocus();
        }
    }//GEN-LAST:event_TxtDireccionKeyPressed

    private void TxtRucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRucKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        this.TxtProducto.requestFocus();     
        //llenarTabla();
        //cargar_datos();
        //limpiar_text();
        
       }
    }//GEN-LAST:event_TxtRucKeyPressed

    private void TxtProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProductoKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        this.TxtCantidad.requestFocus();
        }
    }//GEN-LAST:event_TxtProductoKeyPressed

    private void TxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantidadKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        this.TxtPrecio.requestFocus();
        //Integer.parseInt()
        //if(TxtCantidad * TxtPrecio());
        }
    }//GEN-LAST:event_TxtCantidadKeyPressed

    private void TxtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        this.TxtProducto.requestFocus();     
        llenarTabla();
        cargar_datos();
        limpiar_text();
       } 
    }//GEN-LAST:event_TxtPrecioKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        llenarTabla();
        cargar_datos();
        limpiar_text();
        //enabled_text(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        //eliminar();
        //llenarTabla();
        int filaseleccionada=TableEvento.getSelectedRow();
       if( filaseleccionada>=0){
       modelo.removeRow(filaseleccionada);
       }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JPanel PanelBtnMain;
    private javax.swing.JPanel PanelBtnSecond;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JTable TableEvento;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombres;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField TxtProducto;
    private javax.swing.JTextField TxtRuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
